### PR TITLE
src: switch from Qt to boost implementation of executeProcess

### PR DESCRIPTION
**Pull request by mlangkabel**
* changed implementation of executeProcess
* unified all different implementations of executeProcess
* separated arg list from command for all calls of executeProcess (this also required to remove quotes that were added to path args because otherwise the Python indexer would mistake absolute paths for relative paths.)
* update expected output for custom command tests

### CODE REVIEW

**Comment by Samathy** [comment]
What is the expected release date for this please?
I'm unable to start using SourceTrail on a new project due to #1129, and I'd very much like too.

**Comment by mlangkabel** [comment]
We are planning to release beta builds next week.

**Comment by Samathy** [comment]
Fab, thanks!

**Comment by wolterlw** [comment]
any updates on the release? having same issues with Python indexing

**Comment by mlangkabel** [comment]
Release [2021.1.30 - Beta](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2021.1.30) should be available now.

**Pull request merged**
