### PR TITLE
PR for Issue #802

### PR DESCRIPTION
**Pull request by Alvoda**
Simple patch for issue #802 
Works fine for me when i open projects. Saves some time.

### CODE REVIEW

**Comment by Alvoda** [comment]
anybody looking into this PR?
if sth is missing please tell me.

**Comment by egraether** [comment]
Took a quick look. The main problem is that you are only covering one of the cases where a filepicker is used. Which might be a good start, I'm not sure at the moment. @mlangkabel and me will talk about this tomorrow.

**Comment by egraether** [comment]
We talked about this. Can you please move your change from `QtMainWindow::openProject()` to the methods of `QtFileDialog` as suggested by @mlangkabel [here](https://github.com/CoatiSoftware/Sourcetrail/issues/802#issuecomment-570891940)?

**Comment by amenonsen** [comment]
The requested change has been made in 0da704e already, so this PR should be closed now.

**Comment by mlangkabel** [comment]
Good point ;)

**Pull request closed without merging**
