### PR TITLE
perf: GetOverviewBundleNodeTypesOrdered to static const variable.

### PR DESCRIPTION
**Pull request by technateNG**
During code review I found potential optimization.
Method getOverviewBundleNodeTypesOrdered is called by function GraphController::bundleNodesByType as vector of enums.
But this is not optimized so in assembly. 

Screenshot_2020-01-05_01-17-15

and unfortunately:
Screenshot_2020-01-05_01-18-28

Function by every call constructs whole vector. 

We can fix that situation by eliminating method call and making vector (array) static and const.  
Result after fix:
Screenshot_2020-01-05_01-14-15
All tests passed.

### CODE REVIEW

**Comment by mlangkabel** [comment]
Thank you for making this improvement! Would it be possible to use `vector<>` instead of `array<>`? That would make it easier to add or remove types because one would only have to change one location in the code instead of 3.

**Comment by technateNG** [comment]
Of course it is possible. But this isn't cost less in terms of performance. 

std::array is just global array with constructed variables copied during initialization (before main in so called sub_main function). Additional pro is size known at compile time in constexpr manner - this can enable further compiler optimizations.   

std::vector is a struct which contains pointer to dynamic allocated array and size_t size.
In sub_main std::vector uses new function to construct elements and fill his array.
In run time this generate additional lea instruction because firstly we need obtain address of struct and then address of dynamic array.
But big pro of vector is single declaration which is convenient when we need change variable.

My first thought was std::array but I'll change code if you prefer std::vector. Please answer me here which implementation I should choose.

**Comment by egraether** [comment]
Does this change actually improve performance in a measurable way? It looks to me that the improvement might be very small. Therefore the switch to `array` really just increases maintenance, as @mlangkabel pointed out.

I think that similar optimizations on the `overview` performance could have more impact, aka. I like how you are thinking, but this specific change doesn't accomplish much in my opinion.

**Comment by technateNG** [comment]
In this case it's right trade off. I'm changing to std::vector.

**Comment by egraether** [comment]
Oh, I was talking about the whole PR. It doesn't seem to make a measurable improvement to me. Did you measure any time improvement?

**Comment by mlangkabel** [comment]
Even if it doesn't make a measurable difference I think it would still be a good idea to make this a static variable to indicate that getting these values doesn't execute any code that could have side effects.

**Comment by technateNG** [comment]
Yes. I done such measure. It's not the hottest and most meaningful (i can even say that's one of v. low impact). I made this PR because it's easy to justify clean local improvement.

**Pull request merged**
