### PR TITLE
Apply clang-format

### PR DESCRIPTION
**Pull request by LouisStAmour**
Applied via git-bash:

```bash
find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\|java\|js\)' -and -not -regex '.*/external/.*' -exec bash -c 'echo "{}" && clang-format.exe -
i --style=file {}' \;
```

... and some selective exclusions in bin of external or generated code.

### CODE REVIEW

**Comment by egraether** [comment]
Didn't look at everything yet. Please remove all changes with `bin` and `testing`, these files are data files and don't need to/should not follow our convention.

Do we want the changes for Java? @mlangkabel

**Comment by LouisStAmour** [comment]
> Please remove all changes with bin and testing, these files are data files and don't need to/should not follow our convention.

Done. Though if these files are ever manually edited, IDEs are increasingly likely to format the code using clang-format which will cause unnecessarily large diffs in those files. 

Ideally we'd want a GitHub PR check that runs clang-format against the changed files in the diff, and we would exclude those we don't expect to follow the clang-format output.

**Comment by egraether** [comment]
> > Please remove all changes with bin and testing, these files are data files and don't need to/should not follow our convention.
> 
> Done. Though if these files are ever manually edited, IDEs are increasingly likely to format the code using clang-format which will cause unnecessarily large diffs in those files.
> 
> Ideally we'd want a GitHub PR check that runs clang-format against the changed files in the diff, and we would exclude those we don't expect to follow the clang-format output.

I wouldn't worry about it at the moment.

The C++ changes look good to me. Please look at Java and `.clang-format` changes @mlangkabel

**Comment by mlangkabel** [comment]
I think it is a good idea to apply clang-format also to the java code. From my side, this PR is ok to be merged.

**Pull request merged**
