### PR TITLE
Tests running under external Catch2 for CTest discovery

### PR DESCRIPTION
**Pull request by LouisStAmour**
Just a suggestion, while I was trying to get things working better in Visual Studio via CMake projects. (In the end, CMake projects in Visual Studio aren't as well-supported as MSBuild ones, it seems.)

Would probably need to update the readme to mention Catch2_DIR and setup. Could also change this so if Catch2 isn't found, tests aren't built.

Alternatively we could look at embedding Catch2's CMake files.

### CODE REVIEW

**Comment by egraether** [comment]
I never used CTest before. Can you provide some insights on advantages please?

**Comment by mlangkabel** [comment]
CTest makes CMake aware of all the test cases. So like you can run `cmake --build` to start the build form your command line, you could run `ctest` to execute all the tests.

**Comment by mlangkabel** [comment]
The CI fails because the docker image does not have catch2 installed. We chose to ship catch2 with Sourcetrail to minimize the complexity of setup for new contributers. 

I think embedding the catch2 repo would be the optimal solution for this pull request. Can you give that a try?

**Comment by LouisStAmour** [comment]
I can, yes, but my preference would be a setup script, pre-build, that downloads dependencies for users if they don’t want to do so manually. This way we could give fewer instructions to users about CMake flags, and perhaps make it so that if the correct dependencies exist and the flag is not specified, the functionality will be built anyway. If Catch2 isn’t found, by that logic, then tests would not get built and a warning would be issued in running CMake configuration.

**Comment by mlangkabel** [comment]
Today I looked into referencing Catch2 directly via git submodules. But if we do that, everyone who wants to build Sourcetrail still has to build the Catch2 project first. Otherwise the `find_package(Catch2 REQUIRED)` command in Sourcetrail's CMakeLists file would not work. 

And as far as I can see you added that line in order to make the CTest discovery work via `catch_discover_tests(${TEST_PROJECT_NAME})`. Correct?

I would like to keep our dependencies as simple as possible. That's why we chose the single header option for Catch2. I mean yes, a build script would be the next best option. But still that leaves room for error (maybe the user has some different console environment or something) and if the user encounters an error within the setup script, he may be discouraged right from the start.

Would there be an option to link Catch2 tests with CTest without having the user build Catch2 first?

**Pull request closed without merging**
