### PR TITLE
Fixing a crash in SharedMemory::ScopedAccess use

### PR DESCRIPTION
**Pull request by TTimo**
The `managed_shared_memory` construction throws a 'not found' exception. Not sure why, or if doing a `boost::interprocess::open_or_create` to patch this up is the right thing to do, but this removes a crash for me.

### CODE REVIEW

**Comment by egraether** [comment]
Took a look at this. I will probably accept this, since it only adds a fallback in case of failure and doesn't degrade current behavior. But I have some questions for future reference, or maybe we can find a better fix:
* Do you know if this issue only appears at one specific `SharedMemory` instance? If yes, which one? Or does it affect all of them?
* What error message do you get in the `ScopedAccess` constructor?

**Comment by TTimo** [comment]
I saw it happen on `srctrlmem_grbg_cllctr_64`, throwing `boost::interprocess::not_found_error`

**Comment by egraether** [comment]
@TTimo Can you please test whether #918 also fixes your issue?

**Comment by egraether** [comment]
My concern with this fix is that I think it could cause the indexer process to write into a new shared memory segment that is not accessed by the application, so data is lost. 

Can you please test whether the resulting index is exactly the same when Sourcetrail runs into this issue?

**Comment by TTimo** [comment]
> Can you please test whether the resulting index is exactly the same when Sourcetrail runs into this issue?

Can you clarify what you need there?

Another one, with https://github.com/CoatiSoftware/Sourcetrail/pull/918 applied, but this PR not applied (just configured to verbose and re-throw):

```
Thread 4 "Sourcetrail" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe37fe700 (LWP 27618)]
0x00007fffef47cf25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffef47cf25 in raise () from /usr/lib/libc.so.6
#1  0x00007fffef466897 in abort () from /usr/lib/libc.so.6
#2  0x00007fffef80081d in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffef80d4da in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fffef80d537 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fffef80d78e in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fffd4002350, tinfo=tinfo@entry=0x555555da6380 <typeinfo for boost::interprocess::interprocess_exception>, dest=dest@entry=0x555555988580 <boost::interprocess::interprocess_exception::~interprocess
_exception()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000055555565f6c7 in SharedMemory::ScopedAccess::ScopedAccess (this=0x7fffe37fdb70, memory=<optimized out>) at /home/timo/Sourcetrail/src/lib/utility/interprocess/SharedMemory.cpp:26
#7  0x000055555598952c in SharedMemoryGarbageCollector::update (this=0x555555ec2560) at /home/timo/Sourcetrail/src/lib/utility/interprocess/SharedMemoryGarbageCollector.cpp:172
#8  0x000055555598cf65 in SharedMemoryGarbageCollector::<lambda()>::operator() (__closure=<optimized out>) at /home/timo/Sourcetrail/src/lib/utility/interprocess/SharedMemoryGarbageCollector.cpp:68
#9  std::__invoke_impl<void, SharedMemoryGarbageCollector::run(const string&)::<lambda()> > (__f=...) at /usr/include/c++/9.2.0/bits/invoke.h:60
#10 std::__invoke<SharedMemoryGarbageCollector::run(const string&)::<lambda()> > (__fn=...) at /usr/include/c++/9.2.0/bits/invoke.h:95
#11 std::thread::_Invoker<std::tuple<SharedMemoryGarbageCollector::run(const string&)::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/9.2.0/thread:244
#12 std::thread::_Invoker<std::tuple<SharedMemoryGarbageCollector::run(const string&)::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/9.2.0/thread:251
#13 std::thread::_State_impl<std::thread::_Invoker<std::tuple<SharedMemoryGarbageCollector::run(const string&)::<lambda()> > > >::_M_run(void) (this=0x555555f10520) at /usr/include/c++/9.2.0/thread:195
#14 0x00007fffef839ee4 in std::execute_native_thread_routine (__p=0x555555f10520) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#15 0x00007fffef95d4cf in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007fffef5402d3 in clone () from /usr/lib/libc.so.6
```

```
ERROR: boost exception thrown at ScopeAccess constructor - srctrlmem_grbg_cllctr_64: No such file or directory                                                                                             [10690/10690]
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
```

**Comment by egraether** [comment]
> > Can you please test whether the resulting index is exactly the same when Sourcetrail runs into this issue?
> 
> Can you clarify what you need there?

Actually, I think I can validate this myself by throwing exceptions in certain situations.

**Comment by egraether** [comment]
Validated it myself. Thanks for implementing!

**Comment by TTimo** [comment]
Great! Feel free to rework the patch btw .. I left some bits commented out etc. in order to make the fix easier to understand and test, but not necessarily a final form for a merge ..

**Pull request merged**
