### PR TITLE
fix misses dependencies that are using optional()

### PR DESCRIPTION
**Pull request by solomon-8**
it's relate to this [issue](https://github.com/CoatiSoftware/Sourcetrail/issues/874).

### CODE REVIEW

**Comment by mlangkabel** [comment]
I'm really eager to merge this one. So during the last couple of days I went and set up some basic gradle tests for Sourcetrail. However, when I now create a build.gradle file that uses 
```
dependencies {
    optional("joda-time:joda-time:2.2")
    testCompile "junit:junit:4.12"
}
```
gradle tells me `could not find method optional()`. @Solomon-8: Can you maybe comment with a minimal build.gradle config that we can use for our tests?

**Comment by egraether** [comment]
@mlangkabel Please look into this yourself or close.

**Comment by LouisStAmour** [comment]
I think I found it. https://github.com/spring-projects/spring-framework/blob/fd8d11c7e3e8e1ea133213504399464b62266eef/buildSrc/src/main/java/org/springframework/build/optional/OptionalDependenciesPlugin.java#L28-L64

Added here:
https://github.com/spring-projects/spring-framework/blob/fd8d11c7e3e8e1ea133213504399464b62266eef/buildSrc/build.gradle#L25-L28

And used extensively in Spring/Spring Framework projects. https://github.com/spring-projects/spring-framework/blob/fd8d11c7e3e8e1ea133213504399464b62266eef/spring-jcl/spring-jcl.gradle#L4-L5

Note that Spring Framework has not upgraded to Gradle 6, but is running Gradle 5. https://github.com/spring-projects/spring-framework/blob/fd8d11c7e3e8e1ea133213504399464b62266eef/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by LouisStAmour** [comment]
Which is to say, that `optional( ... )` syntax is non-standard and not what this PR fixes directly.

This PR, if I'm guessing correctly, is about gradle maven support marking dependencies as optional:

https://issues.gradle.org/browse/GRADLE-1749
https://github.com/gradle/gradle/issues/867
and as pointed out earlier, feature variants: https://docs.gradle.org/5.3.1/userguide/feature_variants.html

Previously the supported method for this was https://github.com/nebula-plugins/gradle-extra-configurations-plugin#usage-example-1 so that's another usage syntax.

**Pull request closed without merging**
