### PR TITLE
logic: save last filepicker location

### LINKED ISSUE #802: Store last filepicker location in application settings
After restarting Sourcetrail this location shall be used as the first default when opening a file picker dialog.

### PR DESCRIPTION
**Pull request by miltolstoy**
Resolves #802

### CODE REVIEW

**Comment by miltolstoy** [comment]
@mlangkabel 

Hi, Malte!
I was guided with [your comment](https://github.com/CoatiSoftware/Sourcetrail/issues/802#issuecomment-570891940) for this PR. Please correct me if something doesn't match your expectations.

Also I'm not familiar with Sourcetrail yet. Can you provide me some user cases to completely check this change?

**Comment by mlangkabel** [comment]
Thank you for working on this! One remark first: Try to avoid using `auto` in the code, we try to keep it explicit to make reading as easy as possible.

Use case:
* open a new instance of Sourcetrail
* create a new project and use the filepicker to select a project directory (e.g. `.../myproject`)
* add a "empty source group" and add an enty in the "Files & Directories to Index" list
* click the "..." button to select a filepath
* the filepicker that shows up shall show the location of the previously selected project dir (e.g. `.../myproject`)
* close the filepicker by picking a subdirectory of the picked project directory (e.g. `.../myproject/mydir`)
* close Sourcetrail without finishing the project setup
* open Sourcetrail again
* create a new project
* when using the filepicker now to select a project directory, it shall initially display the directory that has been picked via filepicker last  (e.g. `.../myproject/mydir`)

**Comment by miltolstoy** [comment]
> Try to avoid using auto in the code, we try to keep it explicit to make reading as easy as possible.

Done.

> * when using the filepicker now to select a project directory, it shall initially display the directory that has been picked via filepicker last (e.g. .../myproject/mydir)

Last step failed. Relaunched app opens user's home directory instead of `.../myproject/mydir`.
I'm launching application directly from build directory: `${build_dir}/app/Sourcetrail`. And I wasn't able to find any file with user settings inside build directory. Can this be an issue?

**Comment by mlangkabel** [comment]
After starting Sourcetrail you can click Help -> Show Log Folder and the parent folder of the folder that opens then should contain an `ApplicationSettings.xml` file that stores all your settings.

**Comment by miltolstoy** [comment]
> After starting Sourcetrail you can click Help -> Show Log Folder and the parent folder of the folder that opens then should contain an `ApplicationSettings.xml` file that stores all your settings.

As I can see, settings are not saved when project setup was not finished. Looks like an adequate behavior - don't save last filepicker location, if project wasn't open in result of its setup.
Do I need to change it? If yes, which implementation variant should be chosen? I see two for now:
1. Update project setup workflow to save settings in case of setup cancel.
2. Save settings to filesystem after each filepicker path update.

**Comment by mlangkabel** [comment]
2

**Comment by miltolstoy** [comment]
I found that different code is used for project directory and source group filepickers. They even have different window titles - "Select Directory" and "Find Directory", respectively. That is a reason why QtFileDialog modified methods are not called in source group directory choosing and "last_filepicker_path" setting is not updated.
I wasn't able to find code, which is called on source group directory selection. Can you help me?

**Comment by mlangkabel** [comment]
For that case, if the user presses the "..." icon in the UI, `QtPathListBoxItem::handleButtonPress()` calls `QtFileDialog::getFileNamesAndDirectories()`

**Comment by miltolstoy** [comment]
> Use case:
> 
>     * open a new instance of Sourcetrail
> 
>     * create a new project and use the filepicker to select a project directory (e.g. `.../myproject`)
> 
>     * add a "empty source group" and add an enty in the "Files & Directories to Index" list
> 
>     * click the "..." button to select a filepath
> 
>     * the filepicker that shows up shall show the location of the previously selected project dir (e.g. `.../myproject`)
> 
>     * close the filepicker by picking a subdirectory of the picked project directory (e.g. `.../myproject/mydir`)
> 
>     * close Sourcetrail without finishing the project setup
> 
>     * open Sourcetrail again
> 
>     * create a new project
> 
>     * when using the filepicker now to select a project directory, it shall initially display the directory that has been picked via filepicker last  (e.g. `.../myproject/mydir`)

It works now.

**Comment by mlangkabel** [comment]
Looks good. Thank you!

**Comment by miltolstoy** [comment]
> Looks good. Thank you!

My pleasure.

**Pull request merged**
