### PR TITLE
Add ScopedAccess check to SharedMemoryGarbageCollector creation

### PR DESCRIPTION
**Pull request by egraether**
alternative to #912

### CODE REVIEW

**Comment by TTimo** [comment]
I've used this instead of #918 for a bit today, did not encounter a crash. I don't have a good reproduction for it, but I'd say this fix is ok.

**Comment by TTimo** [comment]
The crash happened again with this morning, while using this patch rather than #918:

```
(gdb) bt
#0  0x00007fffef47cf25 in raise () from /usr/lib/libc.so.6
#1  0x00007fffef466897 in abort () from /usr/lib/libc.so.6
#2  0x00007fffef80081d in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffef80d4da in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fffef80d537 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fffef80d78e in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fffd0006290, tinfo=tinfo@entry=0x555555da8300 <typeinfo for boost::interprocess::interprocess_exception>, dest=dest@entry=0x55555597fa40 <boost::interprocess::interprocess_exception::~int
erprocess_exception()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x0000555555986e2e in boost::interprocess::shared_memory_object::priv_open_or_create (perm=..., mode=boost::interprocess::read_write, filename=<optimized out>, type=boost::interprocess::ipcdetail::DoOpen, this=0x7fffe08184f0) at /usr/include/boost/int
erprocess/shared_memory_object.hpp:363
#7  boost::interprocess::shared_memory_object::shared_memory_object (mode=boost::interprocess::read_write, name=<optimized out>, this=0x7fffe08184f0) at /usr/include/boost/interprocess/shared_memory_object.hpp:83
#8  boost::interprocess::ipcdetail::managed_open_or_create_impl<boost::interprocess::shared_memory_object, 16ul, true, false>::priv_open_or_create<boost::interprocess::ipcdetail::create_open_func<boost::interprocess::ipcdetail::basic_managed_memory_impl<c
har, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0ul>, 0ul>, boost::interprocess::iset_index, 16ul> > > (this=this@entry=0x7fffe08186a8, type=type@entry=boost::interpro
cess::ipcdetail::DoOpen, id=@0x7fffe08185f8: 0x7fffd0003c50 "srctrlmem_icmd_307a27ef-c614", size=size@entry=0, mode=mode@entry=boost::interprocess::read_write, addr=addr@entry=0x0, perm=..., construct_func=...) at /usr/include/boost/interprocess/detail/ma
naged_open_or_create_impl.hpp:339
#9  0x000055555597ecea in boost::interprocess::ipcdetail::managed_open_or_create_impl<boost::interprocess::shared_memory_object, 16ul, true, false>::managed_open_or_create_impl<boost::interprocess::ipcdetail::create_open_func<boost::interprocess::ipcdetai
l::basic_managed_memory_impl<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0ul>, 0ul>, boost::interprocess::iset_index, 16ul> > > (construct_func=..., addr=0x0, mod
e=boost::interprocess::read_write, id=@0x7fffe08185f8: 0x7fffd0003c50 "srctrlmem_icmd_307a27ef-c614", this=0x7fffe08186a8) at /usr/include/boost/interprocess/permissions.hpp:100
#10 boost::interprocess::basic_managed_shared_memory<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0ul>, 0ul>, boost::interprocess::iset_index>::basic_managed_share
d_memory (addr=0x0, name=<optimized out>, this=0x7fffe08186a0) at /usr/include/boost/interprocess/managed_shared_memory.hpp:151
#11 SharedMemory::ScopedAccess::ScopedAccess (this=0x7fffe0818690, memory=0x7fffa67fece8) at /home/timo/Sourcetrail/src/lib/utility/interprocess/SharedMemory.cpp:13
```

```
(gdb) frame 11
#11 SharedMemory::ScopedAccess::ScopedAccess (this=0x7fffe0818690, memory=0x7fffa67fece8) at /home/timo/Sourcetrail/src/lib/utility/interprocess/SharedMemory.cpp:13
(gdb) print memory->getMemoryName()
$6 = "srctrlmem_icmd_307a27ef-c614"
```

**Comment by TTimo** [comment]
Do I understand this change correctly - will this only affect Sourcetrail when "Multi Process C/C++ Indexing" is enable?

**Comment by egraether** [comment]
No. Actually we always use shared memory for C/C++ indexing, even in single process.

We didn't want to put in the time back then and didn't want to maintain 2 implementations. I think it could be implemented in a couple hours. Do you think we need an option to not use shared memory?

**Comment by TTimo** [comment]
> Do you think we need an option to not use shared memory?

No probably not, I was just trying to understand the patterns.

**Comment by egraether** [comment]
#912 was merged instead. Closing.

**Pull request closed without merging**
