### PR TITLE
Fix Clang include path detection on Gentoo

### PR DESCRIPTION
**Pull request by dhallas**
On Gentoo Linux Clang headers are installed in

LLVM_BINARY_DIR/include/clang

i.e.

/usr/lib/llvm/11/include/clang

### CODE REVIEW

**Comment by mlangkabel** [comment]
Thanks for adding this. I'd like to make sure that the directory contains the correct files before merging this. Can you please post a list of the file names that you find in that directory on Gentoo?

**Comment by dhallas** [comment]
> Thanks for adding this. I'd like to make sure that the directory contains the correct files before merging this. Can you please post a list of the file names that you find in that directory on Gentoo?

Here is the contents of LLVM_BINARY_DIR/include/clang on my Gentoo installation
`Analysis    AST          Basic    Config   DirectoryWatcher  Edit    Frontend      Index  Parse    Sema           StaticAnalyzer  Tooling
ARCMigrate  ASTMatchers  CodeGen  CrossTU  Driver            Format  FrontendTool  Lex    Rewrite  Serialization  Testing`

Let me know if there is anything else you need :)

**Comment by mlangkabel** [comment]
Thanks for the reply. I already thought that there may have been a misunderstanding. Each compiler uses its own set of basic header files to compile the target code. E.g. the Visual Studio compiler would compile your code with a different set of basic header files than the clang compiler. 
When Sourcetrail indexes the target code, it uses the Clang compiler, so it needs to ship with a copy of those headers. The get this done, the `CLANG_COMPILER_HEADER_SEARCH_PATH ` should contain the path to the compiler headers of the clang compiler.

The directory you specified looks like it contains the headers used to compile clang, which is not what we need here. For me (Windows 10, Clang 11) the compiler header directory contains the following files and directories:

```
adxintrin.h                                    
altivec.h                                      
ammintrin.h                                    
amxintrin.h                                    
arm64intr.h                                    
armintr.h                                      
arm_acle.h                                     
arm_bf16.h                                     
arm_cde.h                                      
arm_cmse.h                                     
arm_fp16.h                                     
arm_mve.h                                      
arm_neon.h                                     
arm_sve.h                                      
avx2intrin.h                                   
avx512bf16intrin.h                             
avx512bitalgintrin.h                           
avx512bwintrin.h                               
avx512cdintrin.h                               
avx512dqintrin.h                               
avx512erintrin.h                               
avx512fintrin.h                                
avx512ifmaintrin.h                             
avx512ifmavlintrin.h                           
avx512pfintrin.h                               
avx512vbmi2intrin.h                            
avx512vbmiintrin.h                             
avx512vbmivlintrin.h                           
avx512vlbf16intrin.h                           
avx512vlbitalgintrin.h                         
avx512vlbwintrin.h                             
avx512vlcdintrin.h                             
avx512vldqintrin.h                             
avx512vlintrin.h                               
avx512vlvbmi2intrin.h                          
avx512vlvnniintrin.h                           
avx512vlvp2intersectintrin.h                   
avx512vnniintrin.h                             
avx512vp2intersectintrin.h                     
avx512vpopcntdqintrin.h                        
avx512vpopcntdqvlintrin.h                      
avxintrin.h                                    
bmi2intrin.h                                   
bmiintrin.h                                    
cet.h                                          
cetintrin.h                                    
cldemoteintrin.h                               
clflushoptintrin.h                             
clwbintrin.h                                   
clzerointrin.h                                 
cpuid.h                                        
cuda_wrappers                                  
emmintrin.h                                    
enqcmdintrin.h                                 
f16cintrin.h                                   
float.h                                        
fma4intrin.h                                   
fmaintrin.h                                    
fxsrintrin.h                                   
gfniintrin.h                                   
htmintrin.h                                    
htmxlintrin.h                                  
ia32intrin.h                                   
immintrin.h                                    
intrin.h                                       
inttypes.h                                     
invpcidintrin.h                                
iso646.h                                       
limits.h                                       
lwpintrin.h                                    
lzcntintrin.h                                  
mm3dnow.h                                      
mmintrin.h                                     
mm_malloc.h                                    
module.modulemap                               
movdirintrin.h                                 
msa.h                                          
mwaitxintrin.h                                 
nmmintrin.h                                    
opencl-c-base.h                                
opencl-c.h                                     
openmp_wrappers                                
pconfigintrin.h                                
pkuintrin.h                                    
pmmintrin.h                                    
popcntintrin.h                                 
ppc_wrappers                                   
prfchwintrin.h                                 
ptwriteintrin.h                                
rdseedintrin.h                                 
rtmintrin.h                                    
s390intrin.h                                   
serializeintrin.h                              
sgxintrin.h                                    
shaintrin.h                                    
smmintrin.h                                    
stdalign.h                                     
stdarg.h                                       
stdatomic.h                                    
stdbool.h                                      
stddef.h                                       
stdint.h                                       
stdnoreturn.h                                  
tbmintrin.h                                    
tgmath.h                                       
tmmintrin.h                                    
tsxldtrkintrin.h                               
unwind.h                                       
vadefs.h                                       
vaesintrin.h                                   
varargs.h                                      
vecintrin.h                                    
vpclmulqdqintrin.h                             
waitpkgintrin.h                                
wasm_simd128.h                                 
wbnoinvdintrin.h                               
wmmintrin.h                                    
x86intrin.h                                    
xmmintrin.h                                    
xopintrin.h                                    
xsavecintrin.h                                 
xsaveintrin.h                                  
xsaveoptintrin.h                               
xsavesintrin.h                                 
xtestintrin.h                                  
__clang_cuda_builtin_vars.h                    
__clang_cuda_cmath.h                           
__clang_cuda_complex_builtins.h                
__clang_cuda_device_functions.h                
__clang_cuda_intrinsics.h                      
__clang_cuda_libdevice_declares.h              
__clang_cuda_math.h                            
__clang_cuda_math_forward_declares.h           
__clang_cuda_runtime_wrapper.h                 
__clang_hip_libdevice_declares.h               
__clang_hip_math.h                             
__clang_hip_runtime_wrapper.h                  
__stddef_max_align_t.h                         
__wmmintrin_aes.h                              
__wmmintrin_pclmul.h                           
```

**Comment by dhallas** [comment]
Hi @mlangkabel  - I hadn't thought about the issue with the runtime files, but after looking a bit more, it turns out that the files needed to build Sourcetrail is in

`/usr/lib/llvm/11/include`

and the runtime files are in

`/usr/lib/clang/11/include`

But I can't see how I can specify the two in the `CMakeLists.txt` file?

**Comment by dhallas** [comment]
@mlangkabel  - I don't think we ever concluded on this one? Did you see my previous comment? I am a little unsure on how to progress on this?

**Comment by mlangkabel** [comment]
Hm, am I right to assume that your CMake fails on `find_package(Clang REQUIRED)`? What is the error message?

**Comment by dhallas** [comment]
Yes - CMake fails with the following error:
```
-- Found LLVM 11.0.1
-- Trying to find Clang compiler headers in '.' build config in directory ''.
CMake Error at CMakeLists.txt:166 (message):
  Unable to copy Clang compiler headers from clang build dir.
```

**Comment by mlangkabel** [comment]
Ok, so `find_package(Clang REQUIRED` should already find the LLVM/Clang header search paths required to compile Sourcetrail and the LLVM/Clang libraries required to link Sourcetrail. The path that this PR adds to the CMakeLists.txt should point to the directory that contains the files that I postet above. If you do that change on your system, can you then build Sourcetrail and also run the C/C++ indexer on some project? A possible test would be to try to index Sourcetrail's code.

**Comment by dhallas** [comment]
Hi @mlangkabel  - thanks for the quick reply! It turns out that this is slightly more complicated than what I initially thought. The headers needed to _build_ Sourcetrail is indeed located in `/usr/lib/llvm/11/include/clang` which corresponds to `${LLVM_BINARY_DIR}/include/clang` - but the headers required to successfully index is in `/usr/lib/clang/11.0.1/include`.
When looking at the CMakeLists.txt file, I think it assumes that the headers needed to compile Sourcetrail also contains the headers needed to index, so there it only looks for a single directory. But in the case of Gentoo they are found in two different directories. Do you have any good ideas on how could support this? Any pointers would be greatly appreciated :)

**Comment by mlangkabel** [comment]
Why do you think that? The CMake uses the `_CLANG_HEADERS_SEARCH_LIST` that you modified in this PR just to find the headers that will be used by Sourcetrail during indexing and copy those files to some directory where Sourcetrail can find them.

**Comment by dhallas** [comment]
Hi @mlangkabel  - what I mean is that on Gentoo these headers are split into two different directories. One directory contains the headers needed to build Sourcetrail the other directory contains the headers needed to index projects at runtime. My patch only finds the directory needed to build Sourcetrail. So, how would I go by specifying a different directory to copy headers from?

**Comment by dhallas** [comment]
Hi @mlangkabel  - I don't think we ever sorted out this pull request Do you need any other information to merge this pull request?

**Comment by mlangkabel** [comment]
I'm sorry, but to me this PR does not make sense. But maybe I did not understand it correctly.  The only reason the build fails for you seems to be that `_CLANG_HEADERS_SEARCH_LIST` is empty. So adding anything will fix the build, but it may cause issues when your build of Sourcetrail is trying to index any C++ code. 
Please change the CMake to set `_CLANG_HEADERS_SEARCH_LIST` to make the CMake use the correct path (e.g. `/usr/lib/clang/11.0.1/include` on your machine).

**Comment by dhallas** [comment]
Hi @mlangkabel - yes, the reason the build is failing is because on Gentoo the Clang runtime files is not stored in any of the directories listed in the `_CLANG_HEADERS_SEARCH_LIST` variable. But after digging a bit more, I can see that I have actually mixed up the build directories and runtime directories of Clang. On Gentoo, the headers for building things using LLVM is in `/usr/lib/llvm/11/include`, but this directory is automatically found and added to the include path by the `find_packge(Clang)` functionality. But the runtime headers for indexing (which is what the `_CLANG_HEADERS_SEARCH_LIST` actually reflects) are found in `/usr/lib/clang/12.0.0/include`. So, if I add that directory to the `_CLANG_HEADERS_SEARCH_LIST` it builds, runs and indexes just fine! So, let me just update the merge request to reflect this.
Let me know if it is still unclear for you :)

**Comment by dhallas** [comment]
Hi @mlangkabel  - did you have a chance to look at the updated pull request? Let me know if this still doesn't make sense to you :)

**Comment by mlangkabel** [comment]
Closing now because repository wil be archived shortly.

**Pull request closed without merging**
