### PR TITLE
Fixes for Clang 10 compatibility (closes #965)

### LINKED ISSUE #965: Upgrade to LLVM/Clang 10.0.0

### PR DESCRIPTION
**Pull request by LouisStAmour**
Closes #965 

Changes in Clang 10 API:

* FrontendAction now gets passed as unique_ptr - see https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html#internal-api-changes
* StringRef was added in a few places - http://llvm.org/docs/ProgrammersManual.html#the-stringref-class
* llvm::make_unique is now std::make_unique: https://reviews.llvm.org/D66259 because LLVM requires C++14

### CODE REVIEW

**Comment by LouisStAmour** [comment]
The build failure of the newer commit is because I'm expecting a Docker image with LLVM/Clang 10 on it. I'm actually kind of shocked the build succeeded against LLVM 9 unchanged. (I didn't test it locally with LLVM 9.)

**Comment by egraether** [comment]
**Note:** The docker container can't be rebuilt yet, because the download for the new release is not available yet: https://releases.llvm.org/10.0.0/

**Comment by LouisStAmour** [comment]
Releases of LLVM appear to have permanently moved to GitHub, at least according to the LLVM Download page linking to an archive there: https://github.com/llvm/llvm-project/releases

**Comment by LouisStAmour** [comment]
Release announcement doesn’t indicate if this is a permanent change but it appears to be so... http://lists.llvm.org/pipermail/llvm-announce/2020-March/000087.html

**Comment by egraether** [comment]
> Release announcement doesn’t indicate if this is a permanent change but it appears to be so... http://lists.llvm.org/pipermail/llvm-announce/2020-March/000087.html

Thank you for the info!

**Comment by mlangkabel** [comment]
Tested your changes on Windows (Cxx indexer is currently not covered by our CI). All looking good for me :)

**Comment by mlangkabel** [comment]
Before we can merge this we need to update our linux CI.

**Pull request merged**
